-- 自动生成 ./excel/R-任务.xlsx(table_task_config)
return {

    [1] = {
        DescEN = "Concluir a 1st recarga,%s/1",
        ID = 1,
        addChipsPer = 200,
        finishNum = 1,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 1,
        taskClass = 9,
        taskDesc = "充值1次",
        taskType = 1,
    },

    [2] = {
        DescEN = "Concluir a 2nd recarga,%s/2",
        ID = 2,
        addChipsPer = 250,
        finishNum = 2,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 2,
        taskClass = 9,
        taskDesc = "充值2次",
        taskType = 1,
    },

    [3] = {
        DescEN = "Concluir a 3rd recarga,%s/3",
        ID = 3,
        addChipsPer = 300,
        finishNum = 3,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 3,
        taskClass = 9,
        taskDesc = "充值3次",
        taskType = 1,
    },

    [4] = {
        DescEN = "Concluir a 4th recarga,%s/4",
        ID = 4,
        addChipsPer = 350,
        finishNum = 4,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 4,
        taskClass = 9,
        taskDesc = "充值4次",
        taskType = 1,
    },

    [5] = {
        DescEN = "Concluir a 5th recarga,%s/5",
        ID = 5,
        addChipsPer = 400,
        finishNum = 5,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 5,
        taskClass = 9,
        taskDesc = "充值5次",
        taskType = 1,
    },

    [6] = {
        DescEN = "Elevar-se ao nível VIP2,%s/2",
        ID = 6,
        addChipsPer = 800,
        finishNum = 2,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 9,
        taskClass = 9,
        taskDesc = "提升至vip2",
        taskType = 2,
    },

    [7] = {
        DescEN = "Retirada uma vez,%s/1",
        ID = 7,
        addChipsPer = 200,
        finishNum = 1,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 6,
        taskClass = 9,
        taskDesc = "提现1次",
        taskType = 3,
    },

    [8] = {
        DescEN = "Retirada duas vezes,%s/2",
        ID = 8,
        addChipsPer = 300,
        finishNum = 2,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 7,
        taskClass = 9,
        taskDesc = "提现2次",
        taskType = 3,
    },

    [9] = {
        DescEN = "Retirada três vezes,%s/3",
        ID = 9,
        addChipsPer = 400,
        finishNum = 3,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 8,
        taskClass = 9,
        taskDesc = "提现3次",
        taskType = 3,
    },

    [10] = {
        DescEN = "Convite 5 jogadores e garanta que todos eles façam uma recarga,%s/5",
        ID = 10,
        addChipsPer = 1700,
        finishNum = 5,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 11,
        taskClass = 9,
        taskDesc = "邀请5位玩家并确保他们都进行了充值",
        taskType = 4,
    },

    [11] = {
        DescEN = "Elevar-se ao nível VIP3,%s/3",
        ID = 11,
        addChipsPer = 1700,
        finishNum = 3,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 10,
        taskClass = 9,
        taskDesc = "提升至vip3",
        taskType = 2,
    },

    [12] = {
        DescEN = "Convite 10 jogadores e garanta que todos eles façam uma recarga,%s/10",
        ID = 12,
        addChipsPer = 3400,
        finishNum = 10,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 12,
        taskClass = 9,
        taskDesc = "邀请10位玩家并确保他们都进行了充值",
        taskType = 4,
    },

    [13] = {
        DescEN = "null",
        ID = 13,
        addChipsPer = 40,
        finishNum = 50,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 1,
        taskClass = 1,
        taskDesc = "下注50次",
        taskType = 5,
    },

    [14] = {
        DescEN = "null",
        ID = 14,
        addChipsPer = 40,
        finishNum = 5,
        finishNum2 = 0,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 2,
        taskClass = 1,
        taskDesc = "共计赢取 X R$",
        taskType = 6,
    },

    [15] = {
        DescEN = "null",
        ID = 15,
        addChipsPer = 40,
        finishNum = 10,
        finishNum2 = 5,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 3,
        taskClass = 1,
        taskDesc = "中奖5倍及以上下注10次",
        taskType = 7,
    },

    [16] = {
        DescEN = "null",
        ID = 16,
        addChipsPer = 40,
        finishNum = 2,
        finishNum2 = 10,
        gameId = 0,
        isShow = 1,
        reward = {},
        sortid = 4,
        taskClass = 1,
        taskDesc = "中奖10倍及以上下注2次",
        taskType = 7,
    },

}
