-- 自动生成 ./excel/R-任务.xlsx(table_task_pass)
return {

    [1] = {
        ID = 1,
        freeDetail = "Worth $1.99 in Coins",
        freeReward = {{["goodNum"] = 3100000, ["goodId"] = 3}},
        level = 1,
        needNum = 10,
        payDetail = "Wild for any chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10024}},
        version = 1,
    },

    [2] = {
        ID = 2,
        freeDetail = "Club Points x200",
        freeReward = {{["goodNum"] = 200, ["goodId"] = 10003}},
        level = 2,
        needNum = 20,
        payDetail = "Club Pass Card 1 Day x 1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 1,
    },

    [3] = {
        ID = 3,
        freeDetail = "Double XP 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 3,
        needNum = 30,
        payDetail = "Double XP 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 1,
    },

    [4] = {
        ID = 4,
        freeDetail = "Chip Case x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 4,
        needNum = 40,
        payDetail = "3-Star Wish Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        version = 1,
    },

    [5] = {
        ID = 5,
        freeDetail = "Worth $2.99 in Coins",
        freeReward = {{["goodNum"] = 6500000, ["goodId"] = 3}},
        level = 5,
        needNum = 50,
        payDetail = "Worth $11.99 in Coins",
        payReward = {{["goodNum"] = 14000000, ["goodId"] = 3}},
        version = 1,
    },

    [6] = {
        ID = 6,
        freeDetail = "VIP Points x50",
        freeReward = {{["goodNum"] = 50, ["goodId"] = 10002}},
        level = 6,
        needNum = 60,
        payDetail = "VIP Points x100",
        payReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        version = 1,
    },

    [7] = {
        ID = 7,
        freeDetail = "1-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100021}},
        level = 7,
        needNum = 70,
        payDetail = "5-Star Chip Case x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        version = 1,
    },

    [8] = {
        ID = 8,
        freeDetail = "Mini Chest x5",
        freeReward = {{["goodNum"] = 5, ["goodId"] = 10012}},
        level = 8,
        needNum = 80,
        payDetail = "Minor Chest x3",
        payReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        version = 1,
    },

    [9] = {
        ID = 9,
        freeDetail = "X2 Level Rewards 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 9,
        needNum = 90,
        payDetail = "X2 Level Rewards 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 1,
    },

    [10] = {
        ID = 10,
        freeDetail = "Trophy Points x29",
        freeReward = {{["goodNum"] = 29, ["goodId"] = 10006}},
        level = 10,
        needNum = 100,
        payDetail = "Trophy Points x49",
        payReward = {{["goodNum"] = 49, ["goodId"] = 10006}},
        version = 1,
    },

    [11] = {
        ID = 11,
        freeDetail = "3% Insurance 30MIN",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 11,
        needNum = 110,
        payDetail = "7% Insurance 30MIN",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 1,
    },

    [12] = {
        ID = 12,
        freeDetail = "Club Points x400",
        freeReward = {{["goodNum"] = 400, ["goodId"] = 10003}},
        level = 12,
        needNum = 120,
        payDetail = "Club Pass Card 1 Day x 1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 1,
    },

    [13] = {
        ID = 13,
        freeDetail = "2-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100022}},
        level = 13,
        needNum = 140,
        payDetail = "3-Star Gold Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100033}},
        version = 1,
    },

    [14] = {
        ID = 14,
        freeDetail = "Mini Chest x10",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10012}},
        level = 14,
        needNum = 160,
        payDetail = "Minor Chest x6",
        payReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        version = 1,
    },

    [15] = {
        ID = 15,
        freeDetail = "Worth $3.99 in Coins",
        freeReward = {{["goodNum"] = 8800000, ["goodId"] = 3}},
        level = 15,
        needNum = 180,
        payDetail = "Worth $14.99 in Coins",
        payReward = {{["goodNum"] = 26000000, ["goodId"] = 3}},
        version = 1,
    },

    [16] = {
        ID = 16,
        freeDetail = "X2 Level Rewards 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 16,
        needNum = 200,
        payDetail = "X2 Level Rewards 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 1,
    },

    [17] = {
        ID = 17,
        freeDetail = "1-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100021}},
        level = 17,
        needNum = 220,
        payDetail = "5-Star Chip Case x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        version = 1,
    },

    [18] = {
        ID = 18,
        freeDetail = "30% Coupon in coin store",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30006}},
        level = 18,
        needNum = 240,
        payDetail = "50% Coupon in coin store",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        version = 1,
    },

    [19] = {
        ID = 19,
        freeDetail = "Chip Case x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 19,
        needNum = 260,
        payDetail = "4-Star Wish Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 1,
    },

    [20] = {
        ID = 20,
        freeDetail = "Minor Chest x3",
        freeReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        level = 20,
        needNum = 280,
        payDetail = "Major Pouch x5",
        payReward = {{["goodNum"] = 5, ["goodId"] = 10010}},
        version = 1,
    },

    [21] = {
        ID = 21,
        freeDetail = "Trophy Points x12",
        freeReward = {{["goodNum"] = 12, ["goodId"] = 10006}},
        level = 21,
        needNum = 300,
        payDetail = "Trophy Points x59",
        payReward = {{["goodNum"] = 59, ["goodId"] = 10006}},
        version = 1,
    },

    [22] = {
        ID = 22,
        freeDetail = "5-Star Fortune Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        level = 22,
        needNum = 330,
        payDetail = "4-Star Gold Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        version = 1,
    },

    [23] = {
        ID = 23,
        freeDetail = "Mini Chest x15",
        freeReward = {{["goodNum"] = 15, ["goodId"] = 10012}},
        level = 23,
        needNum = 360,
        payDetail = "Major Pouch x2",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10010}},
        version = 1,
    },

    [24] = {
        ID = 24,
        freeDetail = "Chip Case x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 24,
        needNum = 390,
        payDetail = "4-Star Wish Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 1,
    },

    [25] = {
        ID = 25,
        freeDetail = "Worth $5.99 in Coins",
        freeReward = {{["goodNum"] = 11300000, ["goodId"] = 3}},
        level = 25,
        needNum = 420,
        payDetail = "Worth $19.99 in Coins",
        payReward = {{["goodNum"] = 33800000, ["goodId"] = 3}},
        version = 1,
    },

    [26] = {
        ID = 26,
        freeDetail = "2-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100022}},
        level = 26,
        needNum = 450,
        payDetail = "5-Star Wish Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100025}},
        version = 1,
    },

    [27] = {
        ID = 27,
        freeDetail = "VIP Points x100",
        freeReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        level = 27,
        needNum = 480,
        payDetail = "VIP Points x300",
        payReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        version = 1,
    },

    [28] = {
        ID = 28,
        freeDetail = "Club Points x600",
        freeReward = {{["goodNum"] = 600, ["goodId"] = 10003}},
        level = 28,
        needNum = 510,
        payDetail = "Club Pass Card 1 Day x 1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 1,
    },

    [29] = {
        ID = 29,
        freeDetail = "Double XP 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 29,
        needNum = 540,
        payDetail = "Double XP 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 1,
    },

    [30] = {
        ID = 30,
        freeDetail = "3-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        level = 30,
        needNum = 570,
        payDetail = "Ordinary Wild Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10025}},
        version = 1,
    },

    [31] = {
        ID = 31,
        freeDetail = "Mini Chest x18",
        freeReward = {{["goodNum"] = 18, ["goodId"] = 10012}},
        level = 31,
        needNum = 600,
        payDetail = "Minor Chest x15",
        payReward = {{["goodNum"] = 15, ["goodId"] = 10011}},
        version = 1,
    },

    [32] = {
        ID = 32,
        freeDetail = "3% Insurance 30MIN",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 32,
        needNum = 630,
        payDetail = "7% Insurance 30MIN",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 1,
    },

    [33] = {
        ID = 33,
        freeDetail = "X2 Level Rewards 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 33,
        needNum = 660,
        payDetail = "X2 Level Rewards 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 1,
    },

    [34] = {
        ID = 34,
        freeDetail = "30% Coupon in coin store",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30006}},
        level = 34,
        needNum = 700,
        payDetail = "100% Coupon in coin store",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30020}},
        version = 1,
    },

    [35] = {
        ID = 35,
        freeDetail = "Worth $7.99 in Coins",
        freeReward = {{["goodNum"] = 14000000, ["goodId"] = 3}},
        level = 35,
        needNum = 740,
        payDetail = "Worth $24.99 in Coins",
        payReward = {{["goodNum"] = 51000000, ["goodId"] = 3}},
        version = 1,
    },

    [36] = {
        ID = 36,
        freeDetail = "VIP Points x300",
        freeReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        level = 36,
        needNum = 780,
        payDetail = "VIP Points x500",
        payReward = {{["goodNum"] = 500, ["goodId"] = 10002}},
        version = 1,
    },

    [37] = {
        ID = 37,
        freeDetail = "Double XP 12H",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 37,
        needNum = 820,
        payDetail = "Double XP 24H",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 1,
    },

    [38] = {
        ID = 38,
        freeDetail = "Trophy Points x24",
        freeReward = {{["goodNum"] = 24, ["goodId"] = 10006}},
        level = 38,
        needNum = 860,
        payDetail = "Trophy Points x71",
        payReward = {{["goodNum"] = 71, ["goodId"] = 10006}},
        version = 1,
    },

    [39] = {
        ID = 39,
        freeDetail = "Chip Case x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 39,
        needNum = 900,
        payDetail = "4-Star Wish Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 1,
    },

    [40] = {
        ID = 40,
        freeDetail = "Minor Chest x6",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        level = 40,
        needNum = 940,
        payDetail = "Major Pouch x8",
        payReward = {{["goodNum"] = 8, ["goodId"] = 10010}},
        version = 1,
    },

    [41] = {
        ID = 41,
        freeDetail = "X2 Level Rewards 24H",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        level = 41,
        needNum = 980,
        payDetail = "X2 Level Rewards 48H",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40021}},
        version = 1,
    },

    [42] = {
        ID = 42,
        freeDetail = "Club Points x600",
        freeReward = {{["goodNum"] = 600, ["goodId"] = 10003}},
        level = 42,
        needNum = 1020,
        payDetail = "Club Pass Card 2 Day x 1",
        payReward = {{["goodNum"] = 2, ["goodId"] = 40031}},
        version = 1,
    },

    [43] = {
        ID = 43,
        freeDetail = "VIP Points x400",
        freeReward = {{["goodNum"] = 400, ["goodId"] = 10002}},
        level = 43,
        needNum = 1060,
        payDetail = "VIP Points x500",
        payReward = {{["goodNum"] = 500, ["goodId"] = 10002}},
        version = 1,
    },

    [44] = {
        ID = 44,
        freeDetail = "3-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        level = 44,
        needNum = 1100,
        payDetail = "5-Star Gold Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100035}},
        version = 1,
    },

    [45] = {
        ID = 45,
        freeDetail = "Worth $9.99 in Coins",
        freeReward = {{["goodNum"] = 18000000, ["goodId"] = 3}},
        level = 45,
        needNum = 1140,
        payDetail = "Worth $34.99 in Coins",
        payReward = {{["goodNum"] = 77000000, ["goodId"] = 3}},
        version = 1,
    },

    [46] = {
        ID = 46,
        freeDetail = "3-Star Wish Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        level = 46,
        needNum = 1180,
        payDetail = "Wish Wild Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10026}},
        version = 1,
    },

    [47] = {
        ID = 47,
        freeDetail = "3% Insurance 30MIN",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 47,
        needNum = 1230,
        payDetail = "7% Insurance 30MIN",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 1,
    },

    [48] = {
        ID = 48,
        freeDetail = "Double XP 24H",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        level = 48,
        needNum = 1270,
        payDetail = "Double XP 48H",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40011}},
        version = 1,
    },

    [49] = {
        ID = 49,
        freeDetail = "X2 Level Rewards 24H",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        level = 49,
        needNum = 1310,
        payDetail = "X2 Level Rewards 48H",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40021}},
        version = 1,
    },

    [50] = {
        ID = 50,
        freeDetail = "Mini Chest x30",
        freeReward = {{["goodNum"] = 30, ["goodId"] = 10012}},
        level = 50,
        needNum = 1350,
        payDetail = "Minor Chest x20",
        payReward = {{["goodNum"] = 20, ["goodId"] = 10011}},
        version = 1,
    },

    [51] = {
        ID = 51,
        freeDetail = "VIP Points x500",
        freeReward = {{["goodNum"] = 500, ["goodId"] = 10002}},
        level = 51,
        needNum = 1390,
        payDetail = "VIP Points x800",
        payReward = {{["goodNum"] = 800, ["goodId"] = 10002}},
        version = 1,
    },

    [52] = {
        ID = 52,
        freeDetail = "50% Coupon in coin store",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 52,
        needNum = 1440,
        payDetail = "100% Coupon in coin store",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30020}},
        version = 1,
    },

    [53] = {
        ID = 53,
        freeDetail = "3-Star Gold Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100033}},
        level = 53,
        needNum = 1480,
        payDetail = "Gold Wild Chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10027}},
        version = 1,
    },

    [54] = {
        ID = 54,
        freeDetail = "Double XP 24H",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        level = 54,
        needNum = 1520,
        payDetail = "Double XP 48H",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40011}},
        version = 1,
    },

    [55] = {
        ID = 55,
        freeDetail = "Worth $11.99 in Coins",
        freeReward = {{["goodNum"] = 22500000, ["goodId"] = 3}},
        level = 55,
        needNum = 1570,
        payDetail = "Worth $49.99 in Coins",
        payReward = {{["goodNum"] = 96000000, ["goodId"] = 3}},
        version = 1,
    },

    [56] = {
        ID = 56,
        freeDetail = "3% Insurance 30MIN",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 56,
        needNum = 1620,
        payDetail = "7% Insurance 30MIN",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 1,
    },

    [57] = {
        ID = 57,
        freeDetail = "Club Points x4000",
        freeReward = {{["goodNum"] = 4000, ["goodId"] = 10003}},
        level = 57,
        needNum = 1660,
        payDetail = "Club Pass Card 3 Day x 1",
        payReward = {{["goodNum"] = 3, ["goodId"] = 40031}},
        version = 1,
    },

    [58] = {
        ID = 58,
        freeDetail = "Trophy Points x35",
        freeReward = {{["goodNum"] = 35, ["goodId"] = 10006}},
        level = 58,
        needNum = 1710,
        payDetail = "Trophy Points x82",
        payReward = {{["goodNum"] = 82, ["goodId"] = 10006}},
        version = 1,
    },

    [59] = {
        ID = 59,
        freeDetail = "Minor Chest x10",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10011}},
        level = 59,
        needNum = 1760,
        payDetail = "Mega Pouch x2",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10009}},
        version = 1,
    },

    [60] = {
        ID = 60,
        freeDetail = "5-Star Gold Chip x1",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100035}},
        level = 60,
        needNum = 1800,
        payDetail = "Wild for any chip x1",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10024}},
        version = 1,
    },

    [61] = {
        ID = 61,
        freeDetail = "",
        freeReward = {{["goodNum"] = 2020000, ["goodId"] = 3}},
        level = 1,
        needNum = 10,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10024}},
        version = 2,
    },

    [62] = {
        ID = 62,
        freeDetail = "",
        freeReward = {{["goodNum"] = 500, ["goodId"] = 10003}},
        level = 2,
        needNum = 40,
        payDetail = "",
        payReward = {{["goodNum"] = 1000, ["goodId"] = 10003}},
        version = 2,
    },

    [63] = {
        ID = 63,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100022}},
        level = 3,
        needNum = 70,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100033}},
        version = 2,
    },

    [64] = {
        ID = 64,
        freeDetail = "",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10012}},
        level = 4,
        needNum = 110,
        payDetail = "",
        payReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        version = 2,
    },

    [65] = {
        ID = 65,
        freeDetail = "",
        freeReward = {{["goodNum"] = 8800000, ["goodId"] = 3}},
        level = 5,
        needNum = 150,
        payDetail = "",
        payReward = {{["goodNum"] = 26000000, ["goodId"] = 3}},
        version = 2,
    },

    [66] = {
        ID = 66,
        freeDetail = "",
        freeReward = {{["goodNum"] = 50, ["goodId"] = 10002}},
        level = 6,
        needNum = 190,
        payDetail = "",
        payReward = {{["goodNum"] = 200, ["goodId"] = 10002}},
        version = 2,
    },

    [67] = {
        ID = 67,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 7,
        needNum = 230,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 2,
    },

    [68] = {
        ID = 68,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100021}},
        level = 8,
        needNum = 270,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 2,
    },

    [69] = {
        ID = 69,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 9,
        needNum = 310,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 2,
    },

    [70] = {
        ID = 70,
        freeDetail = "",
        freeReward = {},
        level = 10,
        needNum = 350,
        payDetail = "",
        payReward = {},
        version = 2,
    },

    [71] = {
        ID = 71,
        freeDetail = "",
        freeReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        level = 11,
        needNum = 400,
        payDetail = "",
        payReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        version = 2,
    },

    [72] = {
        ID = 72,
        freeDetail = "",
        freeReward = {{["goodNum"] = 800, ["goodId"] = 10003}},
        level = 12,
        needNum = 450,
        payDetail = "",
        payReward = {{["goodNum"] = 2000, ["goodId"] = 10003}},
        version = 2,
    },

    [73] = {
        ID = 73,
        freeDetail = "",
        freeReward = {{["goodNum"] = 15, ["goodId"] = 10012}},
        level = 13,
        needNum = 500,
        payDetail = "",
        payReward = {{["goodNum"] = 5, ["goodId"] = 10011}},
        version = 2,
    },

    [74] = {
        ID = 74,
        freeDetail = "",
        freeReward = {},
        level = 14,
        needNum = 550,
        payDetail = "",
        payReward = {},
        version = 2,
    },

    [75] = {
        ID = 75,
        freeDetail = "",
        freeReward = {{["goodNum"] = 18000000, ["goodId"] = 3}},
        level = 15,
        needNum = 600,
        payDetail = "",
        payReward = {{["goodNum"] = 42000000, ["goodId"] = 3}},
        version = 2,
    },

    [76] = {
        ID = 76,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100013}},
        level = 16,
        needNum = 670,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        version = 2,
    },

    [77] = {
        ID = 77,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 17,
        needNum = 740,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 2,
    },

    [78] = {
        ID = 78,
        freeDetail = "",
        freeReward = {},
        level = 18,
        needNum = 810,
        payDetail = "",
        payReward = {},
        version = 2,
    },

    [79] = {
        ID = 79,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 19,
        needNum = 880,
        payDetail = "",
        payReward = {{["goodNum"] = 400, ["goodId"] = 10002}},
        version = 2,
    },

    [80] = {
        ID = 80,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        level = 20,
        needNum = 950,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10027}},
        version = 2,
    },

    [81] = {
        ID = 81,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 21,
        needNum = 1020,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 2,
    },

    [82] = {
        ID = 82,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        level = 22,
        needNum = 1090,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100025}},
        version = 2,
    },

    [83] = {
        ID = 83,
        freeDetail = "",
        freeReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        level = 23,
        needNum = 1160,
        payDetail = "",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10010}},
        version = 2,
    },

    [84] = {
        ID = 84,
        freeDetail = "",
        freeReward = {},
        level = 24,
        needNum = 1230,
        payDetail = "",
        payReward = {},
        version = 2,
    },

    [85] = {
        ID = 85,
        freeDetail = "",
        freeReward = {{["goodNum"] = 33800000, ["goodId"] = 3}},
        level = 25,
        needNum = 1300,
        payDetail = "",
        payReward = {{["goodNum"] = 77000000, ["goodId"] = 3}},
        version = 2,
    },

    [86] = {
        ID = 86,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 26,
        needNum = 1400,
        payDetail = "",
        payReward = {{["goodNum"] = 432, ["goodId"] = 40011}},
        version = 2,
    },

    [87] = {
        ID = 87,
        freeDetail = "",
        freeReward = {{["goodNum"] = 2000, ["goodId"] = 10003}},
        level = 27,
        needNum = 1500,
        payDetail = "",
        payReward = {{["goodNum"] = 3000, ["goodId"] = 10003}},
        version = 2,
    },

    [88] = {
        ID = 88,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 28,
        needNum = 1600,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 2,
    },

    [89] = {
        ID = 89,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        level = 29,
        needNum = 1700,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10009}},
        version = 2,
    },

    [90] = {
        ID = 90,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100025}},
        level = 30,
        needNum = 1800,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100035}},
        version = 2,
    },

    [91] = {
        ID = 91,
        freeDetail = "",
        freeReward = {{["goodNum"] = 2020000, ["goodId"] = 3}},
        level = 1,
        needNum = 10,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10024}},
        version = 3,
    },

    [92] = {
        ID = 92,
        freeDetail = "",
        freeReward = {{["goodNum"] = 200, ["goodId"] = 10003}},
        level = 2,
        needNum = 20,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 3,
    },

    [93] = {
        ID = 93,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 3,
        needNum = 40,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 3,
    },

    [94] = {
        ID = 94,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 4,
        needNum = 60,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        version = 3,
    },

    [95] = {
        ID = 95,
        freeDetail = "",
        freeReward = {{["goodNum"] = 3100000, ["goodId"] = 3}},
        level = 5,
        needNum = 80,
        payDetail = "",
        payReward = {{["goodNum"] = 18000000, ["goodId"] = 3}},
        version = 3,
    },

    [96] = {
        ID = 96,
        freeDetail = "",
        freeReward = {{["goodNum"] = 50, ["goodId"] = 10002}},
        level = 6,
        needNum = 100,
        payDetail = "",
        payReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        version = 3,
    },

    [97] = {
        ID = 97,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100021}},
        level = 7,
        needNum = 120,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        version = 3,
    },

    [98] = {
        ID = 98,
        freeDetail = "",
        freeReward = {{["goodNum"] = 5, ["goodId"] = 10012}},
        level = 8,
        needNum = 140,
        payDetail = "",
        payReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        version = 3,
    },

    [99] = {
        ID = 99,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 9,
        needNum = 160,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 3,
    },

    [100] = {
        ID = 100,
        freeDetail = "",
        freeReward = {},
        level = 10,
        needNum = 180,
        payDetail = "",
        payReward = {},
        version = 3,
    },

    [101] = {
        ID = 101,
        freeDetail = "",
        freeReward = {{["goodNum"] = 29, ["goodId"] = 10006}},
        level = 11,
        needNum = 200,
        payDetail = "",
        payReward = {{["goodNum"] = 49, ["goodId"] = 10006}},
        version = 3,
    },

    [102] = {
        ID = 102,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100013}},
        level = 12,
        needNum = 220,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10025}},
        version = 3,
    },

    [103] = {
        ID = 103,
        freeDetail = "",
        freeReward = {{["goodNum"] = 300, ["goodId"] = 10003}},
        level = 13,
        needNum = 240,
        payDetail = "",
        payReward = {{["goodNum"] = 1000, ["goodId"] = 10003}},
        version = 3,
    },

    [104] = {
        ID = 104,
        freeDetail = "",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10012}},
        level = 14,
        needNum = 260,
        payDetail = "",
        payReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        version = 3,
    },

    [105] = {
        ID = 105,
        freeDetail = "",
        freeReward = {{["goodNum"] = 4200000, ["goodId"] = 3}},
        level = 15,
        needNum = 280,
        payDetail = "",
        payReward = {{["goodNum"] = 22500000, ["goodId"] = 3}},
        version = 3,
    },

    [106] = {
        ID = 106,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 16,
        needNum = 300,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [107] = {
        ID = 107,
        freeDetail = "",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10012}},
        level = 17,
        needNum = 320,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        version = 3,
    },

    [108] = {
        ID = 108,
        freeDetail = "",
        freeReward = {{["goodNum"] = 400, ["goodId"] = 10003}},
        level = 18,
        needNum = 340,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 3,
    },

    [109] = {
        ID = 109,
        freeDetail = "",
        freeReward = {{["goodNum"] = 50, ["goodId"] = 10002}},
        level = 19,
        needNum = 360,
        payDetail = "",
        payReward = {{["goodNum"] = 150, ["goodId"] = 10002}},
        version = 3,
    },

    [110] = {
        ID = 110,
        freeDetail = "",
        freeReward = {},
        level = 20,
        needNum = 380,
        payDetail = "",
        payReward = {},
        version = 3,
    },

    [111] = {
        ID = 111,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 21,
        needNum = 400,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 3,
    },

    [112] = {
        ID = 112,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100021}},
        level = 22,
        needNum = 420,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        version = 3,
    },

    [113] = {
        ID = 113,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30006}},
        level = 23,
        needNum = 440,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        version = 3,
    },

    [114] = {
        ID = 114,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 24,
        needNum = 460,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 3,
    },

    [115] = {
        ID = 115,
        freeDetail = "",
        freeReward = {{["goodNum"] = 5300000, ["goodId"] = 3}},
        level = 25,
        needNum = 480,
        payDetail = "",
        payReward = {{["goodNum"] = 26000000, ["goodId"] = 3}},
        version = 3,
    },

    [116] = {
        ID = 116,
        freeDetail = "",
        freeReward = {{["goodNum"] = 50, ["goodId"] = 10002}},
        level = 26,
        needNum = 500,
        payDetail = "",
        payReward = {{["goodNum"] = 200, ["goodId"] = 10002}},
        version = 3,
    },

    [117] = {
        ID = 117,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 27,
        needNum = 520,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 3,
    },

    [118] = {
        ID = 118,
        freeDetail = "",
        freeReward = {{["goodNum"] = 500, ["goodId"] = 10003}},
        level = 28,
        needNum = 540,
        payDetail = "",
        payReward = {{["goodNum"] = 1200, ["goodId"] = 10003}},
        version = 3,
    },

    [119] = {
        ID = 119,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 29,
        needNum = 560,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [120] = {
        ID = 120,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100015}},
        level = 30,
        needNum = 580,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10025}},
        version = 3,
    },

    [121] = {
        ID = 121,
        freeDetail = "",
        freeReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        level = 31,
        needNum = 600,
        payDetail = "",
        payReward = {{["goodNum"] = 5, ["goodId"] = 10010}},
        version = 3,
    },

    [122] = {
        ID = 122,
        freeDetail = "",
        freeReward = {{["goodNum"] = 12, ["goodId"] = 10006}},
        level = 32,
        needNum = 620,
        payDetail = "",
        payReward = {{["goodNum"] = 59, ["goodId"] = 10006}},
        version = 3,
    },

    [123] = {
        ID = 123,
        freeDetail = "",
        freeReward = {{["goodNum"] = 70, ["goodId"] = 10002}},
        level = 33,
        needNum = 640,
        payDetail = "",
        payReward = {{["goodNum"] = 200, ["goodId"] = 10002}},
        version = 3,
    },

    [124] = {
        ID = 124,
        freeDetail = "",
        freeReward = {{["goodNum"] = 15, ["goodId"] = 10012}},
        level = 34,
        needNum = 660,
        payDetail = "",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10010}},
        version = 3,
    },

    [125] = {
        ID = 125,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6500000, ["goodId"] = 3}},
        level = 35,
        needNum = 680,
        payDetail = "",
        payReward = {{["goodNum"] = 33800000, ["goodId"] = 3}},
        version = 3,
    },

    [126] = {
        ID = 126,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 36,
        needNum = 700,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 3,
    },

    [127] = {
        ID = 127,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100022}},
        level = 37,
        needNum = 720,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100025}},
        version = 3,
    },

    [128] = {
        ID = 128,
        freeDetail = "",
        freeReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        level = 38,
        needNum = 740,
        payDetail = "",
        payReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        version = 3,
    },

    [129] = {
        ID = 129,
        freeDetail = "",
        freeReward = {{["goodNum"] = 600, ["goodId"] = 10003}},
        level = 39,
        needNum = 760,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 40031}},
        version = 3,
    },

    [130] = {
        ID = 130,
        freeDetail = "",
        freeReward = {},
        level = 40,
        needNum = 780,
        payDetail = "",
        payReward = {},
        version = 3,
    },

    [131] = {
        ID = 131,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 41,
        needNum = 800,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 3,
    },

    [132] = {
        ID = 132,
        freeDetail = "",
        freeReward = {{["goodNum"] = 100, ["goodId"] = 10002}},
        level = 42,
        needNum = 820,
        payDetail = "",
        payReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        version = 3,
    },

    [133] = {
        ID = 133,
        freeDetail = "",
        freeReward = {{["goodNum"] = 700, ["goodId"] = 10003}},
        level = 43,
        needNum = 840,
        payDetail = "",
        payReward = {{["goodNum"] = 2000, ["goodId"] = 10003}},
        version = 3,
    },

    [134] = {
        ID = 134,
        freeDetail = "",
        freeReward = {{["goodNum"] = 15, ["goodId"] = 10012}},
        level = 44,
        needNum = 860,
        payDetail = "",
        payReward = {{["goodNum"] = 5, ["goodId"] = 10011}},
        version = 3,
    },

    [135] = {
        ID = 135,
        freeDetail = "",
        freeReward = {{["goodNum"] = 8800000, ["goodId"] = 3}},
        level = 45,
        needNum = 880,
        payDetail = "",
        payReward = {{["goodNum"] = 42000000, ["goodId"] = 3}},
        version = 3,
    },

    [136] = {
        ID = 136,
        freeDetail = "",
        freeReward = {{["goodNum"] = 18, ["goodId"] = 10012}},
        level = 46,
        needNum = 900,
        payDetail = "",
        payReward = {{["goodNum"] = 15, ["goodId"] = 10011}},
        version = 3,
    },

    [137] = {
        ID = 137,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 47,
        needNum = 920,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [138] = {
        ID = 138,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 48,
        needNum = 940,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 3,
    },

    [139] = {
        ID = 139,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30006}},
        level = 49,
        needNum = 960,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30020}},
        version = 3,
    },

    [140] = {
        ID = 140,
        freeDetail = "",
        freeReward = {},
        level = 50,
        needNum = 980,
        payDetail = "",
        payReward = {},
        version = 3,
    },

    [141] = {
        ID = 141,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        level = 51,
        needNum = 1000,
        payDetail = "",
        payReward = {{["goodNum"] = 8, ["goodId"] = 10010}},
        version = 3,
    },

    [142] = {
        ID = 142,
        freeDetail = "",
        freeReward = {{["goodNum"] = 150, ["goodId"] = 10002}},
        level = 52,
        needNum = 1020,
        payDetail = "",
        payReward = {{["goodNum"] = 400, ["goodId"] = 10002}},
        version = 3,
    },

    [143] = {
        ID = 143,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40011}},
        level = 53,
        needNum = 1040,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        version = 3,
    },

    [144] = {
        ID = 144,
        freeDetail = "",
        freeReward = {{["goodNum"] = 24, ["goodId"] = 10006}},
        level = 54,
        needNum = 1060,
        payDetail = "",
        payReward = {{["goodNum"] = 71, ["goodId"] = 10006}},
        version = 3,
    },

    [145] = {
        ID = 145,
        freeDetail = "",
        freeReward = {{["goodNum"] = 11300000, ["goodId"] = 3}},
        level = 55,
        needNum = 1080,
        payDetail = "",
        payReward = {{["goodNum"] = 51000000, ["goodId"] = 3}},
        version = 3,
    },

    [146] = {
        ID = 146,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100000}},
        level = 56,
        needNum = 1100,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        version = 3,
    },

    [147] = {
        ID = 147,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100013}},
        level = 57,
        needNum = 1120,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        version = 3,
    },

    [148] = {
        ID = 148,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 58,
        needNum = 1140,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [149] = {
        ID = 149,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 59,
        needNum = 1160,
        payDetail = "",
        payReward = {{["goodNum"] = 400, ["goodId"] = 10002}},
        version = 3,
    },

    [150] = {
        ID = 150,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100033}},
        level = 60,
        needNum = 1180,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10027}},
        version = 3,
    },

    [151] = {
        ID = 151,
        freeDetail = "",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        level = 61,
        needNum = 1200,
        payDetail = "",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40021}},
        version = 3,
    },

    [152] = {
        ID = 152,
        freeDetail = "",
        freeReward = {{["goodNum"] = 800, ["goodId"] = 10003}},
        level = 62,
        needNum = 1220,
        payDetail = "",
        payReward = {{["goodNum"] = 2, ["goodId"] = 40031}},
        version = 3,
    },

    [153] = {
        ID = 153,
        freeDetail = "",
        freeReward = {{["goodNum"] = 200, ["goodId"] = 10002}},
        level = 63,
        needNum = 1240,
        payDetail = "",
        payReward = {{["goodNum"] = 500, ["goodId"] = 10002}},
        version = 3,
    },

    [154] = {
        ID = 154,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100022}},
        level = 64,
        needNum = 1260,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        version = 3,
    },

    [155] = {
        ID = 155,
        freeDetail = "",
        freeReward = {{["goodNum"] = 14000000, ["goodId"] = 3}},
        level = 65,
        needNum = 1280,
        payDetail = "",
        payReward = {{["goodNum"] = 60000000, ["goodId"] = 3}},
        version = 3,
    },

    [156] = {
        ID = 156,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        level = 66,
        needNum = 1300,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100025}},
        version = 3,
    },

    [157] = {
        ID = 157,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 67,
        needNum = 1320,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [158] = {
        ID = 158,
        freeDetail = "",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        level = 68,
        needNum = 1340,
        payDetail = "",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40011}},
        version = 3,
    },

    [159] = {
        ID = 159,
        freeDetail = "",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        level = 69,
        needNum = 1360,
        payDetail = "",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40021}},
        version = 3,
    },

    [160] = {
        ID = 160,
        freeDetail = "",
        freeReward = {},
        level = 70,
        needNum = 1380,
        payDetail = "",
        payReward = {},
        version = 3,
    },

    [161] = {
        ID = 161,
        freeDetail = "",
        freeReward = {{["goodNum"] = 30, ["goodId"] = 10012}},
        level = 71,
        needNum = 1400,
        payDetail = "",
        payReward = {{["goodNum"] = 20, ["goodId"] = 10011}},
        version = 3,
    },

    [162] = {
        ID = 162,
        freeDetail = "",
        freeReward = {{["goodNum"] = 144, ["goodId"] = 40021}},
        level = 72,
        needNum = 1420,
        payDetail = "",
        payReward = {{["goodNum"] = 288, ["goodId"] = 40021}},
        version = 3,
    },

    [163] = {
        ID = 163,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1000, ["goodId"] = 10003}},
        level = 73,
        needNum = 1440,
        payDetail = "",
        payReward = {{["goodNum"] = 3000, ["goodId"] = 10003}},
        version = 3,
    },

    [164] = {
        ID = 164,
        freeDetail = "",
        freeReward = {{["goodNum"] = 3, ["goodId"] = 10011}},
        level = 74,
        needNum = 1460,
        payDetail = "",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10010}},
        version = 3,
    },

    [165] = {
        ID = 165,
        freeDetail = "",
        freeReward = {{["goodNum"] = 18000000, ["goodId"] = 3}},
        level = 75,
        needNum = 1480,
        payDetail = "",
        payReward = {{["goodNum"] = 77000000, ["goodId"] = 3}},
        version = 3,
    },

    [166] = {
        ID = 166,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 76,
        needNum = 1500,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [167] = {
        ID = 167,
        freeDetail = "",
        freeReward = {{["goodNum"] = 300, ["goodId"] = 10002}},
        level = 77,
        needNum = 1520,
        payDetail = "",
        payReward = {{["goodNum"] = 800, ["goodId"] = 10002}},
        version = 3,
    },

    [168] = {
        ID = 168,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 78,
        needNum = 1540,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 30020}},
        version = 3,
    },

    [169] = {
        ID = 169,
        freeDetail = "",
        freeReward = {{["goodNum"] = 288, ["goodId"] = 40011}},
        level = 79,
        needNum = 1560,
        payDetail = "",
        payReward = {{["goodNum"] = 576, ["goodId"] = 40011}},
        version = 3,
    },

    [170] = {
        ID = 170,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100024}},
        level = 80,
        needNum = 1580,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10026}},
        version = 3,
    },

    [171] = {
        ID = 171,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 40051}},
        level = 81,
        needNum = 1600,
        payDetail = "",
        payReward = {{["goodNum"] = 6, ["goodId"] = 40061}},
        version = 3,
    },

    [172] = {
        ID = 172,
        freeDetail = "",
        freeReward = {{["goodNum"] = 2000, ["goodId"] = 10003}},
        level = 82,
        needNum = 1620,
        payDetail = "",
        payReward = {{["goodNum"] = 3, ["goodId"] = 40031}},
        version = 3,
    },

    [173] = {
        ID = 173,
        freeDetail = "",
        freeReward = {{["goodNum"] = 10, ["goodId"] = 10011}},
        level = 83,
        needNum = 1640,
        payDetail = "",
        payReward = {{["goodNum"] = 2, ["goodId"] = 10009}},
        version = 3,
    },

    [174] = {
        ID = 174,
        freeDetail = "",
        freeReward = {{["goodNum"] = 35, ["goodId"] = 10006}},
        level = 84,
        needNum = 1660,
        payDetail = "",
        payReward = {{["goodNum"] = 82, ["goodId"] = 10006}},
        version = 3,
    },

    [175] = {
        ID = 175,
        freeDetail = "",
        freeReward = {{["goodNum"] = 26000000, ["goodId"] = 3}},
        level = 85,
        needNum = 1680,
        payDetail = "",
        payReward = {{["goodNum"] = 115000000, ["goodId"] = 3}},
        version = 3,
    },

    [176] = {
        ID = 176,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 30010}},
        level = 86,
        needNum = 1700,
        payDetail = "",
        payReward = {{["goodNum"] = 432, ["goodId"] = 40011}},
        version = 3,
    },

    [177] = {
        ID = 177,
        freeDetail = "",
        freeReward = {{["goodNum"] = 3000, ["goodId"] = 10003}},
        level = 87,
        needNum = 1720,
        payDetail = "",
        payReward = {{["goodNum"] = 5000, ["goodId"] = 10003}},
        version = 3,
    },

    [178] = {
        ID = 178,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100023}},
        level = 88,
        needNum = 1740,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 100035}},
        version = 3,
    },

    [179] = {
        ID = 179,
        freeDetail = "",
        freeReward = {{["goodNum"] = 6, ["goodId"] = 10011}},
        level = 89,
        needNum = 1770,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10009}},
        version = 3,
    },

    [180] = {
        ID = 180,
        freeDetail = "",
        freeReward = {{["goodNum"] = 1, ["goodId"] = 100034}},
        level = 90,
        needNum = 1800,
        payDetail = "",
        payReward = {{["goodNum"] = 1, ["goodId"] = 10024}},
        version = 3,
    },

}
