-- 自动生成 ./excel/S-商城.xlsx(table_shop_config)
return {

    [101] = {
        Fonte = "Recarrega",
        ID = 101,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 3000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 3000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [102] = {
        Fonte = "Recarrega",
        ID = 102,
        VisualPrice = 100,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 2,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 5000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 5100, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [103] = {
        Fonte = "Recarrega",
        ID = 103,
        VisualPrice = 300,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 3,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 10000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 10300, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [104] = {
        Fonte = "Recarrega",
        ID = 104,
        VisualPrice = 800,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 4,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 20000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 20800, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [105] = {
        Fonte = "Recarrega",
        ID = 105,
        VisualPrice = 2000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 4,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 50000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 52000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [106] = {
        Fonte = "Recarrega",
        ID = 106,
        VisualPrice = 5000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 5,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 100000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 105000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [107] = {
        Fonte = "Recarrega",
        ID = 107,
        VisualPrice = 30000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 6,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 500000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 530000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [108] = {
        Fonte = "Recarrega",
        ID = 108,
        VisualPrice = 80000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 8,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 1000000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 1080000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [109] = {
        Fonte = "Recarrega",
        ID = 109,
        VisualPrice = 270000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 9,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 3000000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 3270000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [110] = {
        Fonte = "Recarrega",
        ID = 110,
        VisualPrice = 500000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 10,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 5000000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 5500000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [111] = {
        Fonte = "Recarrega",
        ID = 111,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 2000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 2000, ["goodId"] = 3}},
        shopType = 1,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [201] = {
        Fonte = "Primeira Recarga",
        ID = 201,
        VisualPrice = 1000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 100,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 3000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 4000, ["goodId"] = 3}},
        shopType = 2,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [202] = {
        Fonte = "Oferta Premium",
        ID = 202,
        VisualPrice = 1500,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 50,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 3000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 4500, ["goodId"] = 3}},
        shopType = 2,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [601] = {
        Fonte = "Copa do Mundo",
        ID = 601,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 5000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 5000, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [602] = {
        Fonte = "Copa do Mundo",
        ID = 602,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 20000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 20000, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [603] = {
        Fonte = "Copa do Mundo",
        ID = 603,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 50000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 50000, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [604] = {
        Fonte = "Copa do Mundo",
        ID = 604,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 100000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 100000, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [605] = {
        Fonte = "Copa do Mundo",
        ID = 605,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 200000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 200000, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [401] = {
        Fonte = "Cofrinho",
        ID = 401,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 0,
        priceType = 1,
        shopGoods = {},
        shopType = 4,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [501] = {
        Fonte = "Oferta Premium",
        ID = 501,
        VisualPrice = 1000,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 100,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 2000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 3000, ["goodId"] = 3}},
        shopType = 2,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [502] = {
        Fonte = "Oferta Premium",
        ID = 502,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 50,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 6000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 6500, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [503] = {
        Fonte = "Oferta Premium",
        ID = 503,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 50,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 7000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 7500, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [511] = {
        Fonte = "Oferta Premium",
        ID = 511,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 75,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 8000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 9000, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [512] = {
        Fonte = "Oferta Premium",
        ID = 512,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 75,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 10000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 11500, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [513] = {
        Fonte = "Oferta Premium",
        ID = 513,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 75,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 12000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 14000, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [521] = {
        Fonte = "Oferta Premium",
        ID = 521,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 150,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 13000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 15500, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [522] = {
        Fonte = "Oferta Premium",
        ID = 522,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 150,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 14000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 17000, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [523] = {
        Fonte = "Oferta Premium",
        ID = 523,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 150,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 15000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 18500, ["goodId"] = 3}},
        shopType = 5,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [301] = {
        Fonte = "Cartão semanal",
        ID = 301,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 9500,
        priceType = 1,
        shopGoods = {{["goodNum"] = 9500, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [302] = {
        Fonte = "Cartão semanal",
        ID = 302,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 18000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 18000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [303] = {
        Fonte = "Cartão semanal",
        ID = 303,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 44000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 44000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [304] = {
        Fonte = "Cartão semanal",
        ID = 304,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 190000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 190000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [305] = {
        Fonte = "Cartão semanal",
        ID = 305,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 490000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 490000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [306] = {
        Fonte = "Cartão semanal",
        ID = 306,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 690000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 690000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [307] = {
        Fonte = "Cartão semanal",
        ID = 307,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 990000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 990000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [308] = {
        Fonte = "Cartão semanal",
        ID = 308,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 1390000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 1390000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [309] = {
        Fonte = "Cartão semanal",
        ID = 309,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 1690000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 1690000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [310] = {
        Fonte = "Cartão semanal",
        ID = 310,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 1990000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 1990000, ["goodId"] = 3}},
        shopType = 3,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [606] = {
        Fonte = "Cartão semanal",
        ID = 606,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 35000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 24500, ["goodId"] = 3}},
        shopType = 6,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [701] = {
        Fonte = "Recarrega",
        ID = 701,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 110,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 10000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 12000, ["goodId"] = 3}, {["goodNum"] = 9000, ["goodId"] = 2}},
        shopType = 7,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [702] = {
        Fonte = "Recarrega",
        ID = 702,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 120,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 20000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 25000, ["goodId"] = 3}, {["goodNum"] = 19000, ["goodId"] = 2}},
        shopType = 7,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [703] = {
        Fonte = "Recarrega",
        ID = 703,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 130,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 30000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 39000, ["goodId"] = 3}, {["goodNum"] = 30000, ["goodId"] = 2}},
        shopType = 7,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [704] = {
        Fonte = "Recarrega",
        ID = 704,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 140,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 40000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 54000, ["goodId"] = 3}, {["goodNum"] = 42000, ["goodId"] = 2}},
        shopType = 7,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [705] = {
        Fonte = "Recarrega",
        ID = 705,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 150,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 50000,
        priceType = 1,
        shopGoods = {{["goodNum"] = 70000, ["goodId"] = 3}, {["goodNum"] = 55000, ["goodId"] = 2}},
        shopType = 7,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [801] = {
        Fonte = "SORTE DIÁRIA",
        ID = 801,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 0,
        priceType = 1,
        shopGoods = {},
        shopType = 8,
        vipClose = 9999999,
        vipOpen = 0,
    },

    [802] = {
        Fonte = "SORTE DIÁRIA",
        ID = 802,
        VisualPrice = 0,
        buffGoods = {},
        buyNbr = 0,
        extGoods = {},
        firstShopGoods = {},
        giftGoods = {},
        iapppayId = 0,
        isCoupon = 0,
        isShow = 1,
        isSpin = 0,
        onShelve = 1,
        price = 0,
        priceType = 1,
        shopGoods = {},
        shopType = 8,
        vipClose = 9999999,
        vipOpen = 0,
    },

}
