-- 自动生成 ./excel/X-新闻热点.xlsx(table_hot_news_set)
return {

    [1] = {
        endTime = "2022-12-1 4:00:00",
        functionName = "庄园",
        id = 1,
        image = "16.png",
        instructions = "每3个月一个活动周期",
        level = 0.0,
        name = "庄园1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Glamor Club\nBenefits",
        type = 1,
        weight = 1,
    },

    [2] = {
        endTime = "2022-9-8 4:00:00",
        functionName = "庄园",
        id = 2,
        image = "manor.png",
        instructions = "根据运营需求不定期开放",
        level = 0.0,
        name = "庄园促销1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "MANOR\nSPECIAL",
        type = 1,
        weight = 2,
    },

    [3] = {
        endTime = "2022-9-2 4:00:00",
        functionName = "JACKPOT REQUITE",
        id = 3,
        image = "j.png",
        instructions = "4种内购活动每种持续1天,轮换",
        level = 0.0,
        name = "内购1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Jackpot\nRequite",
        type = 1,
        weight = 3,
    },

    [4] = {
        endTime = "2022-9-3 4:00:00",
        functionName = "ECHO RETURN",
        id = 4,
        image = "e.png",
        instructions = "4种内购活动每种持续1天,轮换",
        level = 0.0,
        name = "内购2",
        registeredTime = 0,
        startTime = "2022-9-2 4:00:00",
        titleName = "ECHO\nReturn",
        type = 1,
        weight = 4,
    },

    [5] = {
        endTime = "2022-9-4 4:00:00",
        functionName = "INSURANCE BAGS(保险袋)",
        id = 5,
        image = "cqd.png",
        instructions = "4种内购活动每种持续1天,轮换",
        level = 0.0,
        name = "内购3",
        registeredTime = 0,
        startTime = "2022-9-3 4:00:00",
        titleName = "Insurance\nReturn",
        type = 1,
        weight = 5,
    },

    [6] = {
        endTime = "2022-9-5 4:00:00",
        functionName = "FREE GAME FURY",
        id = 6,
        image = "mf.png",
        instructions = "4种内购活动每种持续1天,轮换",
        level = 0.0,
        name = "内购4",
        registeredTime = 0,
        startTime = "2022-9-4 4:00:00",
        titleName = "Free Games\nFury",
        type = 1,
        weight = 6,
    },

    [7] = {
        endTime = "2022-9-15 4:00:00",
        functionName = "每日任务(SECRET ISLAND)",
        id = 7,
        image = "cm.png",
        instructions = "每14天换1个新的活动美宣",
        level = 20.0,
        name = "任务1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "SECRET ISLAND\nSEASON",
        type = 1,
        weight = 7,
    },

    [8] = {
        endTime = "2022-9-29 4:00:00",
        functionName = "每日任务(CROWN DAY)",
        id = 8,
        image = "mission_2.png",
        instructions = "每14天换1个新的活动美宣",
        level = 20.0,
        name = "任务2",
        registeredTime = 0,
        startTime = "2022-9-15 4:00:00",
        titleName = "CROWN DAY\nSEASON",
        type = 1,
        weight = 8,
    },

    [9] = {
        endTime = "2022-10-13 4:00:00",
        functionName = "每日任务(DREAM CITY)",
        id = 9,
        image = "mission_1.png",
        instructions = "每14天换1个新的活动美宣",
        level = 20.0,
        name = "任务3",
        registeredTime = 0,
        startTime = "2022-9-29 4:00:00",
        titleName = "DREAM CITY\nSEASON",
        type = 1,
        weight = 9,
    },

    [10] = {
        endTime = "2022-10-27 4:00:00",
        functionName = "每日任务(COUNTRY TRAVEL)",
        id = 10,
        image = "mission_3.png",
        instructions = "每14天换1个新的活动美宣",
        level = 20.0,
        name = "任务4",
        registeredTime = 0,
        startTime = "2022-10-13 4:00:00",
        titleName = "COUNTRY TRAVEL\nSEASON",
        type = 1,
        weight = 10,
    },

    [11] = {
        endTime = "2022-9-6 4:00:00",
        functionName = "宾果",
        id = 11,
        image = "bingo.png",
        instructions = "3个活动每个持续5天,轮换",
        level = 40.0,
        name = "宾果1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "BINGO IS\nON",
        type = 1,
        weight = 11,
    },

    [12] = {
        endTime = "2022-9-11 4:00:00",
        functionName = "捕鱼",
        id = 12,
        image = "13.png",
        instructions = "3个活动每个持续5天,轮换",
        level = 40.0,
        name = "捕鱼1",
        registeredTime = 0,
        startTime = "2022-9-6 4:00:00",
        titleName = "FISHING\nEXPERT",
        type = 1,
        weight = 12,
    },

    [13] = {
        endTime = "2022-9-16 4:00:00",
        functionName = "烹饪",
        id = 13,
        image = "14.png",
        instructions = "3个活动每个持续5天,轮换",
        level = 40.0,
        name = "烹饪大师1",
        registeredTime = 0,
        startTime = "2022-9-11 4:00:00",
        titleName = "Cooking\nChallenge",
        type = 1,
        weight = 13,
    },

    [14] = {
        endTime = "2025-9-16 4:00:00",
        functionName = "商城",
        id = 14,
        image = "cx.png",
        instructions = "根据运营需求不定期展示",
        level = 0.0,
        name = "商城1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Cost Effective\nProducts",
        type = 1,
        weight = 14,
    },

    [15] = {
        endTime = "2025-9-16 4:00:00",
        functionName = "存钱罐",
        id = 15,
        image = "cqg.png",
        instructions = "根据运营需求不定期展示",
        level = 0.0,
        name = "存钱罐1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Piggy Card\nRevel",
        type = 1,
        weight = 15,
    },

    [16] = {
        endTime = "2025-9-16 4:00:00",
        functionName = "粉丝页",
        id = 16,
        image = "sq.png",
        instructions = "一直存在",
        level = 0.0,
        name = "粉丝页1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "CWS\nFan page",
        type = 1,
        weight = 16,
    },

    [17] = {
        endTime = "2022-9-30 4:00:00",
        functionName = "VIP",
        id = 17,
        image = "vip.png",
        instructions = "根据运营需求不定期展示",
        level = 0.0,
        name = "VIP1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Boost\nFor You",
        type = 1,
        weight = 17,
    },

    [18] = {
        endTime = "2025-9-16 4:00:00",
        functionName = "积分榜",
        id = 18,
        image = "match_1.png",
        instructions = "每7天一个活动周期",
        level = 35.0,
        name = "积分榜1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "GLAMOR\nMATCH",
        type = 1,
        weight = 18,
    },

    [19] = {
        endTime = "",
        functionName = "新手探索",
        id = 19,
        image = "ts.png",
        instructions = "新玩家注册之时持续3天",
        level = 0.0,
        name = "新手探索",
        registeredTime = 3,
        startTime = "",
        titleName = "Quest is\nComing",
        type = 2,
        weight = 19,
    },

    [20] = {
        endTime = "2022-9-8 4:00:00",
        functionName = "探索(丛林)",
        id = 20,
        image = "ts2.png",
        instructions = "3种探索主题每种持续7天,轮换.(新玩家显示新手探索后直接同步当前探索主题)",
        level = 5.0,
        name = "探索1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "Questing\nFor Prize",
        type = 1,
        weight = 20,
    },

    [21] = {
        endTime = "2022-9-15 4:00:00",
        functionName = "探索(神话)",
        id = 21,
        image = "ts3.png",
        instructions = "3种探索主题每种持续7天,轮换.(新玩家显示新手探索后直接同步当前探索主题)",
        level = 5.0,
        name = "探索2",
        registeredTime = 0,
        startTime = "2022-9-8 4:00:00",
        titleName = "Questing\nFor Prize",
        type = 1,
        weight = 21,
    },

    [22] = {
        endTime = "2022-9-22 4:00:00",
        functionName = "探索(赌场)",
        id = 22,
        image = "ts.png",
        instructions = "3种探索主题每种持续7天,轮换.(新玩家显示新手探索后直接同步当前探索主题)",
        level = 5.0,
        name = "探索3",
        registeredTime = 0,
        startTime = "2022-9-15 4:00:00",
        titleName = "Questing\nFor Prize",
        type = 1,
        weight = 22,
    },

    [23] = {
        endTime = "2025-9-16 4:00:00",
        functionName = "商城邮票",
        id = 23,
        image = "xy.png",
        instructions = "根据运营需求不定期展示",
        level = 0.0,
        name = "商城邮票1",
        registeredTime = 0,
        startTime = "2022-9-1 4:00:00",
        titleName = "MORE\nCOINS",
        type = 1,
        weight = 23,
    },

}
