-- 自动生成 ./excel/B-Buff.xlsx(table_buff_config)
return {

    [1001] = {
        ID = 1001,
        desc = "当天最高奖池金币返还（有上限）",
        icon = "",
        name = "BUFF 奖池回赠",
        number = 0,
        para1 = "200",
        para2 = "",
        pri = 1,
        time = 0,
        type = 1,
    },

    [1004] = {
        ID = 1004,
        desc = "当天最高奖池金币返还（有上限）",
        icon = "",
        name = "BUFF 奖池回赠",
        number = 0,
        para1 = "500",
        para2 = "",
        pri = 2,
        time = 0,
        type = 1,
    },

    [1007] = {
        ID = 1007,
        desc = "当天最高奖池金币返还（有上限）",
        icon = "",
        name = "BUFF 奖池回赠",
        number = 0,
        para1 = "99999",
        para2 = "",
        pri = 3,
        time = 0,
        type = 1,
    },

    [1002] = {
        ID = 1002,
        desc = "当天最高免费游戏金币返还（有上限）",
        icon = "",
        name = "BUFF 免费回赠",
        number = 0,
        para1 = "2",
        para2 = "",
        pri = 0,
        time = 0,
        type = 2,
    },

    [1003] = {
        ID = 1003,
        desc = "当天最高基础游戏金币返还（有上限）",
        icon = "",
        name = "BUFF 大奖回赠",
        number = 0,
        para1 = "100",
        para2 = "",
        pri = 0,
        time = 0,
        type = 3,
    },

    [1011] = {
        ID = 1011,
        desc = "获得经验值*2",
        icon = "",
        name = "BUFF 双倍经验加成时长5m",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1021] = {
        ID = 1021,
        desc = "升级奖励*2",
        icon = "",
        name = "BUFF 升级奖励加成时长5m",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1031] = {
        ID = 1031,
        desc = "俱乐部开启1天",
        icon = "",
        name = "BUFF 俱乐部开启1天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1041] = {
        ID = 1041,
        desc = "vip提升1等级",
        icon = "",
        name = "BUFF VIP提升一个等级",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1042] = {
        ID = 1042,
        desc = "表示俱乐部开启",
        icon = "",
        name = "BUFF 俱乐部为开启状态",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1051] = {
        ID = 1051,
        desc = "当天未中奖的下注金额按一定比例返还",
        icon = "",
        name = "BUFF 保险袋3%时长5m",
        number = 0,
        para1 = "0.03",
        para2 = "",
        pri = 0,
        time = 0,
        type = 4,
    },

    [1061] = {
        ID = 1061,
        desc = "当天未中奖的下注金额按一定比例返还",
        icon = "",
        name = "BUFF 保险袋7%时长5m",
        number = 0,
        para1 = "0.07",
        para2 = "",
        pri = 0,
        time = 0,
        type = 4,
    },

    [1071] = {
        ID = 1071,
        desc = "当天未中奖的下注金额按一定比例返还",
        icon = "",
        name = "BUFF 保险袋10%时长5m",
        number = 0,
        para1 = "0.1",
        para2 = "",
        pri = 0,
        time = 0,
        type = 4,
    },

    [1081] = {
        ID = 1081,
        desc = "当天未中奖的下注金额按一定比例返还",
        icon = "",
        name = "BUFF 保险袋15%时长5m",
        number = 0,
        para1 = "0.15",
        para2 = "",
        pri = 0,
        time = 0,
        type = 4,
    },

    [1091] = {
        ID = 1091,
        desc = "当天未中奖的下注金额按一定比例返还",
        icon = "",
        name = "BUFF 保险袋20%时长5m",
        number = 0,
        para1 = "0.2",
        para2 = "",
        pri = 0,
        time = 0,
        type = 4,
    },

    [1100] = {
        ID = 1100,
        desc = "获得（积分榜的）积分*2",
        icon = "",
        name = "BUFF 积分榜积分翻倍10m",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1101] = {
        ID = 1101,
        desc = "获得（探索任务的）进度*2",
        icon = "",
        name = "BUFF 探索任务进度翻倍10m",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1199] = {
        ID = 1199,
        desc = "获得（通行证的）进度*2",
        icon = "",
        name = "BUFF 通行证进度翻倍",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 1800,
        type = 0,
    },

    [1200] = {
        ID = 1200,
        desc = "获得（通行证的）进度*2",
        icon = "",
        name = "BUFF 通行证进度翻倍",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 900,
        type = 0,
    },

    [1201] = {
        ID = 1201,
        desc = "下注满进度获得食材币*2",
        icon = "",
        name = "BUFF 烹饪大师-食材币翻倍器",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1202] = {
        ID = 1202,
        desc = "（购物篮）食材币兑换食材数*2",
        icon = "",
        name = "BUFF 烹饪大师-兑换食材+1",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1211] = {
        ID = 1211,
        desc = "",
        icon = "",
        name = "BUFF 巨龙宝藏-宝剑翻倍器",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1212] = {
        ID = 1212,
        desc = "",
        icon = "",
        name = "BUFF 巨龙宝藏-金币翻倍器",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1221] = {
        ID = 1221,
        desc = "下注满进度获得入场券*2",
        icon = "",
        name = "BUFF 捕鱼大师-门票翻倍器",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1222] = {
        ID = 1222,
        desc = "金币奖励*2（除了海洋地图和小鱼收购商）",
        icon = "",
        name = "BUFF 捕鱼大师-金币翻倍器",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1223] = {
        ID = 1223,
        desc = "后续3次海域，中等至少1贝壳，豪华至少2贝壳",
        icon = "",
        name = "BUFF 捕鱼大师-超级捕鱼家",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1231] = {
        ID = 1231,
        desc = "下注满进度获得宾果球*2",
        icon = "",
        name = "BUFF 宾果-1",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1232] = {
        ID = 1232,
        desc = "卡片上未中且无特殊图标的数字都带宝箱",
        icon = "",
        name = "BUFF 宾果-2",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1233] = {
        ID = 1233,
        desc = "摇出的数字为必中万能符号",
        icon = "",
        name = "BUFF 宾果-3",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1311] = {
        ID = 1311,
        desc = "商城购买绿钻额外获得一定比例",
        icon = "",
        name = "BUFF 神像-铜国王",
        number = 0,
        para1 = "0.3",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1312] = {
        ID = 1312,
        desc = "商城购买获得的收集物数量增加",
        icon = "",
        name = "BUFF 神像-银国王",
        number = 0,
        para1 = "2",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1313] = {
        ID = 1313,
        desc = "商城购买获得的收集物保底星级增加",
        icon = "",
        name = "BUFF 神像-金国王",
        number = 0,
        para1 = "1",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1321] = {
        ID = 1321,
        desc = "收集物商店价格乘一定比例",
        icon = "",
        name = "BUFF 神像-铜王后",
        number = 0,
        para1 = "0.9",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1322] = {
        ID = 1322,
        desc = "超级转盘（nado）中的金币乘一定比例",
        icon = "",
        name = "BUFF 神像-银王后",
        number = 0,
        para1 = "2",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1323] = {
        ID = 1323,
        desc = "收集物集齐一组（10个）奖励乘一定比例",
        icon = "",
        name = "BUFF 神像-金王后",
        number = 0,
        para1 = "2",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1401] = {
        ID = 1401,
        desc = "购买了通行证",
        icon = "",
        name = "BUFF 通行证",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1402] = {
        ID = 1402,
        desc = "购买了双倍通行证",
        icon = "",
        name = "BUFF 双倍通行证",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1501] = {
        ID = 1501,
        desc = "获得（调整的）钻石*2",
        icon = "",
        name = "BUFF 挑战钻石翻倍",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1601] = {
        ID = 1601,
        desc = "救济金轮盘、水果机金币加成100%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1602] = {
        ID = 1602,
        desc = "救济金轮盘、水果机金币加成90%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1603] = {
        ID = 1603,
        desc = "救济金轮盘、水果机金币加成80%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1604] = {
        ID = 1604,
        desc = "救济金轮盘、水果机金币加成70%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1605] = {
        ID = 1605,
        desc = "救济金轮盘、水果机金币加成60%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1606] = {
        ID = 1606,
        desc = "救济金轮盘、水果机金币加成50%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1607] = {
        ID = 1607,
        desc = "救济金轮盘、水果机金币加成40%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1608] = {
        ID = 1608,
        desc = "救济金轮盘、水果机金币加成30%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1609] = {
        ID = 1609,
        desc = "救济金轮盘、水果机金币加成20%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1610] = {
        ID = 1610,
        desc = "救济金轮盘、水果机金币加成10%",
        icon = "",
        name = "BUFF 积分榜救济金加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1611] = {
        ID = 1611,
        desc = "商城金币加成50%",
        icon = "",
        name = "积分榜商城金币加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1612] = {
        ID = 1612,
        desc = "商城金币加成40%",
        icon = "",
        name = "积分榜商城金币加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1613] = {
        ID = 1613,
        desc = "商城金币加成30%",
        icon = "",
        name = "积分榜商城金币加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1614] = {
        ID = 1614,
        desc = "商城金币加成20%",
        icon = "",
        name = "积分榜商城金币加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

    [1615] = {
        ID = 1615,
        desc = "商城金币加成10%",
        icon = "",
        name = "积分榜商城金币加成7天",
        number = 0,
        para1 = "",
        para2 = "",
        pri = 0,
        time = 0,
        type = 0,
    },

}
